---
- hosts: master_node
  become: yes
  roles:
    - common
    - docker
    - riemers.ansible-gitlab-runner
      # - zabbix_server
    - zabbix_agent
  
  tasks:
    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Add gitlab-runner user to the Docker group
      user:
        name: gitlab-runner
        groups: docker
        append: yes
