- name: Install Zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Copy Zabbix agent configuration
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    force: yes

- name: Ensure Zabbix agent is running and enabled
  service:
    name: zabbix-agent
    state: started
    enabled: yes

